# Generated by Django 5.1 on 2024-09-08 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingApp', '0003_consultancyproject_cv_personaldetails_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='teacher_id',
            field=models.CharField(default='0', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='teacher_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_path',
            field=models.ImageField(upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='publications',
            field=models.FileField(upload_to='publicationss'),
        ),
    ]
