# Generated by Django 5.1 on 2024-09-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingApp', '0004_cv_teacher_id_publications_teacher_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='id',
        ),
        migrations.AlterField(
            model_name='cv',
            name='teacher_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
