# Generated by Django 5.1 on 2024-09-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingApp', '0006_remove_personaldetails_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancyproject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='id',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AlterField(
            model_name='consultancyproject',
            name='teacher_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='teacher_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publications',
            name='teacher_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='teacher_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='teacher_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
