# Generated by Django 5.1 on 2024-09-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingApp', '0007_remove_consultancyproject_id_remove_profile_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultancyProject',
        ),
        migrations.DeleteModel(
            name='publications',
        ),
        migrations.DeleteModel(
            name='ResearchProject',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
