# Generated by Django 5.1 on 2024-09-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingApp', '0008_delete_consultancyproject_delete_publications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=255)),
                ('name_of_project', models.CharField(max_length=255)),
                ('type_of_grant', models.CharField(max_length=255)),
                ('funding_organization', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('publications', models.FileField(upload_to='publicationss')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=255)),
                ('name_of_project', models.CharField(max_length=255)),
                ('type_of_grant', models.CharField(max_length=255)),
                ('funding_organization', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
